### ISSUE TITLE
Sample CEF file

### ISSUE THREAD

**Issue by bsuwal** [uscensusbureau/census2020-das-2010ddp#10]
My understanding is that the Census Edited File is a format from within the census and it is not made public. 
**Is it possible to get a sample CEF file in order to inspect what it looks like?** 

My specific use case is this:
I have a bunch of reconstructions of a 2010 state that I would like to run through DDP. I was planning to build them as suggested by the format at the bottom of this file: `https://github.com/uscensusbureau/census2020-das-e2e/blob/master/programs/reader/e2e_reader.py` Even a key to what these fields mean would be helpful, i think.

but I dont understand where I would enter geographic data like say the Block Group a person is in. 

I am familiar with the 1940s IPUMs data format where the Household lines contain the geographic information.

**Comment by garfi303** [comment]
"Thank you for your question.  The 2020 Data Products were created from an internal file, not from the CEF. The reader that created these products is documented here:

*    https://github.com/uscensusbureau/census2020-das-2010ddp/blob/master/das_decennial/configs/full_person/dhcpDemoProductConfig_fixedTotals.ini#L55

Which you can find here:

*    https://github.com/uscensusbureau/census2020-das-2010ddp/blob/058d8daf07463c6d3d079036c945271af55d1fa6/das_decennial/programs/reader/table_reader.py#L425

From this, you should have enough information to create your own reader to read your files, or to format your files into a form that can be read by table_reader.py.

The next version of the 2020 DAS that we publish will have the specifications for the CEF contained in our source code. If you wish, we can publish our current version of this file, but we cannot guarantee that it will interoperate with the code that you are working with.

Regarding the e2e_reader: you can modify this program to add additional geographies. The geography is represented as a 'geocode'. You can define this code as a concatenation of any geographies that you wish, and the geographic levels are defined as string operations on this string.

Regarding Block Groups - the block group is the first digit of the 4-digit block number. If you have reconstructed the state, county, tract and block, then you have the block group.

Thank you for your interest in the 2020 DAS.

Simson Garfinkel
