### ISSUE TITLE
Noising 0 population blocks

### ISSUE THREAD

**Issue by bsuwal** [uscensusbureau/census2020-das-2010ddp#12]
Is it correct to say that blocks that have a population of 0 are not treated with the DP mechanism?

It seems like the reader works by reading in  the person lines from the input file, which means that 0 population blocks never get represented anywhere in the system. This also means that 0 population blocks do not get noised at all, and stay 0.

Is this the correct way to interpret the code, and if not, where are the 0 population blocks being accounted for?

**Comment by garfi303** [comment]
Blocks with 0 units (i.e., 0 Housing Units and 0 GQ facilities) always have 0 population (and this behavior cannot be altered without editing the DAS source code); for blocks with >0 units but 0 population (which implies 0 GQ facilities, as only Housing Units can be vacant), whether the MDF can have >0 population in these blocks depends on whether a block-level total population invariant is specified in the DAS config file.

In the code release associated with the 2010DDP, blocks that have 0 units cannot have >0 population in the MDF. Blocks with 0 population but with >0 vacant Housing Units have positive probability of having >0 population in the MDF, however (for epsilon <infinity), so long as a block-level total population invariant is not specified in the configuration file.

That this is so is not immediately obvious on reviewing the reader code, which (as `bsuwal` correctly points out) infers the universe of valid geocodes from the ingested microdata. But, importantly, the DAS reads microdata for both Persons _and_ Units, and performs a right-outer join that preserves geocodes identified in the latter but not in the former. The key line to review, containing this right-outer join, is:
https://github.com/uscensusbureau/census2020-das-2010ddp/blob/058d8daf07463c6d3d079036c945271af55d1fa6/das_decennial/programs/reader/table_reader.py#L562
