### ISSUE TITLE
Which levels get allocated the privacy budget in the DAS E2E example? 

### ISSUE THREAD

**Issue by pwayner** [uscensusbureau/census2020-das-2010ddp#3]
When using the DAS E2E example AMI, I noticed the documentation embedded in the CONFIG.ini file in das_decennnial says that the privacy budget is split "in topdown order (e.g. County, Tract, Block Group, Block)". But the certificate produced at the end of the run says that it is split between: Enumdist, county, state and national. Is one correct?

**Comment by simsongcensus** [comment]
This is also a question on the E2E release, which is located here: https://github.com/uscensusbureau/census2020-das-e2e

The information printed on the certificate may be printed in the reverse order. We will need to research this and get back to you.

**Comment by garfi303** [comment]
The E2E release was run with the [2018 config file ](https://github.com/uscensusbureau/census2020-das-e2e/blob/master/E2E_2018_CONFIG.ini) to produce the data that were published. Outside of the Census Bureau it can only be run with the [1940 config file](https://github.com/uscensusbureau/census2020-das-e2e/blob/master/E2E_1940_CONFIG.ini). 

For 2018, the US Census Bureau ran the program with the privacy loss budget split between the County (Providence), Tract, Block Group and Block. 

The 1940 data from IPUMS does not have tract or block group coding: it has enumeration districts. Therefore the 1940 config file splits the privacy loss budget between national, state, county, and enumdist. 

The ordering is from top down. If the certificate prints in the other order, it is in error and needs to be corrected.
