### ISSUE TITLE
Where is the set up script? 

### ISSUE THREAD

**Issue by pwayner** [uscensusbureau/census2020-das-2010ddp#4]
The documentation on census2020-das-2010ddp/das_decennial/README.md says that there's a script:  das_decennail/etc/setup_external but I can't find anything in das_decennial/etc/ but a README.md file.

**Comment by garfi303** [comment]
The documentation was copied over from the E2E release but the script was not. You can use the scripts from the E2E release here:

https://github.com/uscensusbureau/census2020-das-e2e/tree/master/etc
