### ISSUE TITLE
How does the noise work at the national level? 

### ISSUE THREAD

**Issue by pwayner** [uscensusbureau/census2020-das-2010ddp#5]
What kind of when the noise is introduced at the top, national level? Isn't it all one big bucket?

**Comment by garfi303** [comment]
Noise is added to every geounit at every geolevel by adding noise to the node's histogram. So noise is added at the national level when noise is added to the national histogram. 

The particular mechanism is specified in the config file and applied to each node here: https://github.com/uscensusbureau/census2020-das-2010ddp/blob/cb482b495b56dd23b1348a4cd5a0aff14d8e6d8c/das_decennial/programs/engine/engine_utils.py#L128
