### ISSUE TITLE
available AMI?

### ISSUE THREAD

**Issue by bsuwal** [uscensusbureau/census2020-das-2010ddp#8]
Is there an Amazon Machine Image publicly available with the configuration used to generate the DDPs?

**Comment by garfi303** [comment]
The 2010DDP was generated using a standard Amazon EMR version 3.25  and Intel Python 3.6.9. We also use Gurobi, which requires a license.  If you check out this repo and install that software, it should work with relatively few problems.  The [prep scripts for the 2018 End-to-End test ](https://github.com/uscensusbureau/census2020-das-e2e/tree/master/etc)will provide additional guidance.

Please let us know if you have additional questions.
