### ISSUE TITLE
dirs `4j` and `ark`

### ISSUE THREAD

**Issue by bsuwal** [uscensusbureau/census2020-das-2010ddp#9]
Running the program gives me error 

`FileNotFoundError: [Errno 2] No such file or directory: '4j/__init__.py'`

when its trying to make a release file. The --print_bom option also lists `4j` and `ark` directories that are not on this repo.

Are they missing or shoul I be getting them from somewhere else?

**Comment by garfi303** [comment]
Thank you for posting this! So that we can assist you, can you please provide:
1. The runtime environment that you are using? For example: version of python, operating system, server environment. 
2. The complete command line you are using, and the full output? I'm not sure what you mean by "Running the program."
3. The complete config file that you are using.
4. A pointer to the input data that you are using.

Thanks!

**Comment by bsuwal** [comment]
Thanks for the quick response! To answer your questions:
1.  Im using python3.6. This is what I get when type `cat /etc/os-release` on the commandline:
`
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/" 
`
I have launched an EC2 instance with the instructions in the E2E readme, so it is a m5.xlarge.

2.  ```/usr/local/anaconda3/bin/python3.6 das2020_driver.py configs/full_person/dhcpDemoProductConfig_fixedTotals.ini```

3.  The config file is exactly the one in ```configs/full_person/dhcpDemoProductConfig_fixedTotals.ini``` .

4.  I am not currently using any input data hehe, because I thought I would worry about that once the program yelled at me for it. I have some reconstructions that I intend to turn into the format specified by the reader in https://github.com/uscensusbureau/census2020-das-e2e/blob/master/programs/reader/e2e_reader.py#L449 . Would that work?

Thanks again for your answers! I realize the instructions ask for an EMR instance but with the node specs in the  design spec the price was very high, so I was hoping to configure  it on an external setup.

**Comment by garfi303** [comment]
Hi. I'm sorry for the delay in getting back to you on this. 

I have pushed https://github.com/uscensusbureau/census2020-das-2010ddp/commit/058d8daf07463c6d3d079036c945271af55d1fa6 which includes minor changes to allow the BOM to be generated outside of the AWS EMR environment. You can validate the config file and the dependencies with this command:

    $ python das2020_driver.py --print_bom configs/census_1940/ipums_1940.ini

To get this operational, I used Anaconda release Jan 8, 2020 (Python 3.7.6) with `conda install pyspark`. 

Note that you can create the BOM without the use of the optimizer. The optimizer runs on the WORKER nodes, and it appears that the `import gurobipy` statement is not being executed when the BOM is generated at this point. 

Can you try to generate a BOM and post the results as an attachment to this issue? I suspect that your unknown `4j` directory is actually a PATH problem and that `py4j` is not set up properly on the version of `pyspark` that you are using. 

I also noticed that you stated that you launched an EC2 instance. The DDP version has not been tested on an EC2 instance running in Spark standalone mode. It is typically run in the EMR environment. If you are running on an EC2 node, then you will have needed to install `pyspark` yourself. How did you do that?

Thank you.

**Comment by bsuwal** [comment]
Hi Simson, I am sorry for the even longer delay in getting back to you!

Thank you for your changes. I have attached the bom.txt generated:
[bom.txt](https://github.com/uscensusbureau/census2020-das-2010ddp/files/4908664/bom.txt)

You were correct in suspecting the unknown 4j directory is a path problem -- I did `conda install pyspark` and now  the `4j` directory has gone away from the bom file. I'm still having issues with the `ark` directory though, perhaps it is a similar problem?

**Comment by garfi303** [comment]
Hi. There is no `ark` directory. This is another issue with your system, I suspect.
You should not need to do a `conda install pyspark`. You should have spark installed on the Amazon EMR cluster that you are using. Our supported configuration is running on Amazon Elastic MapReduce with Anaconda Python. Is that not the configuration you are using?
